resources:
  - type: storage.v1.bucket
    name: sls-forumalura-dev-1710526818396
    properties:
      location: us-central1
  - type: gcp-types/cloudfunctions-v1:projects.locations.functions
    name: forumalura-dev-recebeAtividade
    properties:
      parent: projects/forumalura-417318/locations/us-central1
      availableMemoryMb: 256
      runtime: nodejs16
      timeout: 60s
      entryPoint: recebeAtividade
      function: forumalura-dev-recebeAtividade
      sourceArchiveUrl: >-
        gs://sls-forumalura-dev-1710526818396/serverless/forumalura/dev/1710868597297-2024-03-19T17:16:37.297Z/forumalura.zip
      labels: {}
      httpsTrigger:
        url: path
  - type: gcp-types/cloudfunctions-v1:projects.locations.functions
    name: forumalura-dev-insereAtividade
    properties:
      parent: projects/forumalura-417318/locations/us-central1
      availableMemoryMb: 256
      runtime: nodejs16
      timeout: 60s
      entryPoint: insereAtividade
      function: forumalura-dev-insereAtividade
      sourceArchiveUrl: >-
        gs://sls-forumalura-dev-1710526818396/serverless/forumalura/dev/1710868597297-2024-03-19T17:16:37.297Z/forumalura.zip
      labels: {}
      eventTrigger:
        eventType: providers/cloud.pubsub/eventTypes/topic.publish
        resource: projects/forumalura-417318/topics/atividades
